// Assign_01_03 - Even Fibonacci.cpp : Defines the entry point for the console application.
/*
Problem 3 (25 points)

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

Design and implement an efficient algorithm that by considering the terms in the Fibonacci sequence whose values do not exceed N, finds the sum of the even-valued terms.
*/

/*	Tyler Quayle  */

#include "stdafx.h"
#include <iostream>

using namespace std;

int main()
{
	int N = 100;
	int sum = 0;
	int current = 1;
	int last = current;

	while(current < N)
	{
		if((current = last + current) < N && current % 2 == 0) sum += current;
		last = current - last;
	}

	cout << "Sum of even valued terms: " << sum << "\n\n";

	system("pause");
	return 0;
}

